# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pepapp Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pepapp Example

 pod 'KokteylUtils'

  target 'Pepapp ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pepapp ExampleUITests' do
    # Pods for testing
  end

end
